<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>GestureSign.ExtraPlugins.ClipboardMatch</RootNamespace>
    <AssemblyName>GestureSign.ClipboardMatch.Plugin</AssemblyName>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\GestureSign.Common\GestureSign.Common.csproj" />
  </ItemGroup>
</Project>
