// <auto-generated />
using System.CodeDom.Compiler;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace GestureSign.ExtraPlugins.TextCopyer.Properties
{
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "10.0.0.0")]
    [CompilerGenerated]
    internal class Resources
    {
        private static ResourceManager resourceManager;
        private static CultureInfo resourceCulture;

        internal static ResourceManager ResourceManager => resourceManager ??=
            new ResourceManager("GestureSign.ExtraPlugins.TextCopyer.Properties.Resources", typeof(Resources).Assembly);

        internal static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string en => ResourceManager.GetString("en", resourceCulture);

        internal static string zh => ResourceManager.GetString("zh", resourceCulture);
    }
}
