<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Configurations>Debug;Release;Portable;uiAccessRelease</Configurations>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Portable'">
    <DefineConstants>$(DefineConstants);Portable</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'uiAccessRelease'">
    <DefineConstants>$(DefineConstants);uiAccess</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)SupportedOSPlatform.cs" Link="Properties\SupportedOSPlatform.cs" />
  </ItemGroup>
</Project>
