<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>GestureSign.Tests.DesktopHost</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\GestureSign.CorePlugins\GestureSign.CorePlugins.csproj" />
  </ItemGroup>
</Project>
