<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>GestureSign.Common</RootNamespace>
    <AssemblyName>GestureSign.Common</AssemblyName>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NuGet.Versioning" Version="7.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GestureSign.PointPatterns\GestureSign.PointPatterns.csproj" />
    <ProjectReference Include="..\ManagedWinapi\ManagedWinapi.csproj" />
  </ItemGroup>
</Project>
