<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>GestureSign.CorePlugins</RootNamespace>
    <AssemblyName>GestureSign.CorePlugins</AssemblyName>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GestureSign.Common\GestureSign.Common.csproj" />
    <ProjectReference Include="..\ManagedWinapi\ManagedWinapi.csproj" />
    <ProjectReference Include="..\WindowsInput\WindowsInput.csproj" />
  </ItemGroup>
</Project>
