<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>GestureSign.Updater</RootNamespace>
    <AssemblyName>GestureSign.Updater</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <NoWarn>$(NoWarn);WFO0003</NoWarn>
  </PropertyGroup>
</Project>
