<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>GestureSign.ReleaseManager</RootNamespace>
    <AssemblyName>GestureSign.ReleaseManager</AssemblyName>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro.IconPacks.Lucide" Version="6.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GestureSign.Common\GestureSign.Common.csproj" />
  </ItemGroup>
</Project>
