<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>GestureSign.ExtraPlugins.TextCopyer</RootNamespace>
    <AssemblyName>GestureSign.ExtraPlugins.TextCopyer</AssemblyName>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\GestureSign.Common\GestureSign.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="crosshair.ico" />
  </ItemGroup>
</Project>
